bitops.h: change __builtin_ffsl to NOT rely on glibc
manually implement __ffs so that we don't rely on built-in function  __builtin_ffsl that may reference to __ffsdi2 in glibc.
The reason is after [this commit](https://github.com/checkpoint-restore/criu/commit/2f50da4389a588ae675830788f9de09ed64fa578) to add `restore_membarrier_registrations` in `criu/pie/restorer.c`, on a X86->RISC-V cross compiling environment, restorer.o has undefined reference to `__ffsdi2` (defined in glibc). But criu/pie has the flag of `CFLAGS_PIE		+= -DCR_NOGLIBC` set in top level Makefile so it cannot rely on __ffsdi2. Thus, we reimplement __ffs without the build-in function that relies on glibc.

Signed-off-by: Yixue Zhao <felicitia2010@gmail.com>